# SPDX-FileCopyrightText: 2025 Freedom FOSS Foundation <https://freedomfoss.org>
#
# SPDX-License-Identifier: GPL-3.0-only

---
policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
      header:
        length: 90
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      conventional:
        types:
          [
            "chore",
            "ci",
            "docs",
            "perf",
            "refactor",
            "style",
            "test",
            "release",
          ]
        scopes: [".*"]
