version = 1

# configurations
[[annotations]]
path = [".github/pull_request_template.md",".markdownlint.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Freedom FOSS Foundation <https://freedomfoss.org>"
SPDX-License-Identifier = "GPL-3.0-only"

# images etc
[[annotations]]
path = ["assets/*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Freedom FOSS Foundation <https://freedomfoss.org>"
SPDX-License-Identifier = "GPL-3.0-only"