#
# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (Please use private disclosure)
title: "[SECURITY]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Disclosure

        **IMPORTANT:** Please do not report security vulnerabilities through public GitHub issues.

        For security vulnerabilities, please follow our responsible disclosure process:

        1. **Private Reporting:** Use GitHub's private vulnerability reporting feature
        2. **Security Email:** Send details to security@broadsage.com
        3. **Security Policy:** Review our complete [Security Policy](../SECURITY.md)

        ---

        **If this is NOT a security vulnerability, please close this issue and use the appropriate template.**

  - type: checkboxes
    id: confirmation
    attributes:
      label: ⚠️ Security Confirmation
      description: Please confirm you understand our security reporting process
      options:
        - label: I understand this form should only be used for reporting security vulnerabilities
          required: true
        - label: I have read the [Security Policy](../SECURITY.md) and will follow responsible disclosure
          required: true
        - label: I will not publicly disclose this vulnerability until it has been addressed
          required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Authentication/Authorization
        - Code Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - SQL Injection
        - Remote Code Execution
        - Privilege Escalation
        - Information Disclosure
        - Denial of Service
        - Cryptographic Issue
        - Supply Chain
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity (CVSS)
      description: What is your estimated severity level?
      options:
        - Critical (9.0-10.0)
        - High (7.0-8.9)
        - Medium (4.0-6.9)
        - Low (0.1-3.9)
        - Unknown
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - Version 1.2.3
        - Version 1.2.4
        - All versions >= 1.0.0
    validations:
      required: true

  - type: textarea
    id: vulnerability-summary
    attributes:
      label: Vulnerability Summary
      description: Provide a brief, non-detailed summary (avoid technical details here)
      placeholder: Brief description of the security issue without revealing exploitation details
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially do?
      placeholder: |
        - Data access/modification
        - System compromise
        - Service disruption
        - etc.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: What environment/configuration is affected?
      placeholder: |
        - Operating System: 
        - Browser/Runtime:
        - Version:
        - Configuration:
    validations:
      required: false

  - type: checkboxes
    id: public-disclosure
    attributes:
      label: Public Disclosure
      description: Have you disclosed this vulnerability anywhere else?
      options:
        - label: This vulnerability has NOT been publicly disclosed
        - label: This vulnerability has NOT been reported to other vendors/platforms
        - label: I commit to coordinated disclosure through the project maintainers

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context that might be helpful (without technical details)
      placeholder: Additional context, references, or background information
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Next Steps

        After submitting this report:

        1. **Acknowledgment:** We will acknowledge receipt within 48 hours
        2. **Assessment:** Our security team will assess the vulnerability
        3. **Communication:** We will provide regular updates on our progress
        4. **Resolution:** We will work to address the issue promptly
        5. **Disclosure:** We will coordinate public disclosure timing with you

        Thank you for helping us keep our project secure! 🛡️
