#
# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Community Health

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request:
    types: [opened, labeled, unlabeled, closed]
  schedule:
    # Run daily at 9 AM UTC to check for stale issues
    - cron: "0 9 * * *"

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  welcome-new-contributors:
    name: Welcome New Contributors
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'

    steps:
      - name: Welcome new issue authors
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            // Check if this is the user's first issue
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.issue.user.login,
              state: 'all'
            });

            if (issues.length === 1) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "👋 Welcome to the community, @" + context.payload.issue.user.login + "! Thank you for opening your first issue. A maintainer will review it soon!"
              });
            }

      - name: Welcome new PR authors
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            // Check if this is the user's first PR
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.payload.pull_request.user.login,
              state: 'all'
            });

            if (prs.length === 1) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "🎉 Thank you for your first pull request, @" + context.payload.pull_request.user.login + "! We're excited to review your contribution."
              });
            }

  triage-issues:
    name: Triage New Issues
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'

    steps:
      - name: Add needs-triage label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-triage']
            });

  manage-stale:
    name: Manage Stale Issues and PRs
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within 7 days."
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within 7 days."
          close-issue-message: "This issue was automatically closed because it has been stale for 7 days with no activity."
          close-pr-message: "This pull request was automatically closed because it has been stale for 7 days with no activity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          days-before-stale: 30
          days-before-close: 7
          operations-per-run: 100

  thank-contributors:
    name: Thank Contributors
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Thank contributor for merged PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            await github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 Thank you, @" + pr.user.login + "! Your contribution has been merged and is now part of the project! 🚀"
            });
