# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage
#
# SPDX-License-Identifier: Apache-2.0

---
name: REUSE Compliance
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    steps:
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 #v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 10

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0
