# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
name: Lint Public Code MetaData
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  publiccode_validation:
    name: publiccode validation
    runs-on: ubuntu-latest
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 #v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 #v4.3.0
      - uses: italia/publiccode-parser-action@33aa2fbd2724e6033a4fc6711fa30a53982daed0 # v1.3.2
        with:
          publiccode: "publiccode.yml"
