# SPDX-FileCopyrightText: 2025 Freedom FOSS Foundation <https://freedomfoss.org>
#
# SPDX-License-Identifier: GPL-3.0-only

---
name: Lint Public Code MetaData
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  publiccode_validation:
    name: publiccode validation
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 #v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: italia/publiccode-parser-action@3244a5a109ae23f76cb379831abbad32927cad8c # v1.2.0
        with:
          publiccode: "publiccode.yml"
