# SPDX-FileCopyrightText: 2025 Freedom FOSS Foundation <https://freedomfoss.org>
#
# SPDX-License-Identifier: GPL-3.0-only

---
name: MegaLinter
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read
  security-events: write

env:
  MEGALINTER_CONFIG: /config/mega-linter.yml

jobs:
  megalinter:
    name: megalint
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'pull_request') && (github.actor != 'dependabot[bot]') }}
    permissions:
      # Needed for Code scanning upload
      security-events: write

    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf #v2.11.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 7

      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter@146333030da68e2e58c6ff826633824fabe01eaf # v8.5.0

      - name: Archive production artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports

      - name: Upload Megalint Sarif Report
        uses: github/codeql-action/upload-sarif@b2e6519679e446e7bb7c3466d70f13a6b5461fcd #v3.26.6
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
