# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage <opensource@broadsage.com>
#
# SPDX-License-Identifier: Apache-2.0

---
name: Release Please

on:
  push:
    tags:
      # Standard semantic versioning (v1.0.0)
      - "v[0-9]+.[0-9]+.[0-9]+"
      # Pre-release versions (v1.0.0-alpha.1, v1.0.0-beta.2, v1.0.0-rc.1)
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      # Development and snapshot builds
      - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-snapshot.[0-9]+"
      # Build metadata (v1.0.0+build.1)
      - 'v[0-9]+.[0-9]+.[0-9]+\+*'
      # Combined pre-release and build metadata
      - "v[0-9]+.[0-9]+.[0-9]+-*\\+*"

permissions: read-all

jobs:
  release-please:
    name: Release Please Automation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/some-build-artifact.zip
