# SPDX-FileCopyrightText: Copyright (c) 2025 Broadsage
#
# SPDX-License-Identifier: Apache-2.0

---
name: Opensource Workflow

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit:
    permissions:
      contents: read
    uses: ./.github/workflows/commit.yml
  license:
    permissions:
      contents: read
    uses: ./.github/workflows/license.yml
  lint:
    permissions:
      contents: read
      security-events: read-all
    uses: ./.github/workflows/lint.yml
  lintpubliccode:
    permissions:
      contents: read
    uses: ./.github/workflows/lint-publiccode.yml
