# SPDX-FileCopyrightText: 2025 Freedom FOSS Foundation <https://freedomfoss.org>
#
# SPDX-License-Identifier: GPL-3.0-only

---
name: FOSS Template Workflow

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit:
    permissions:
      contents: read
    uses: ./.github/workflows/commit.yml
  license:
    permissions:
      contents: read
    uses: ./.github/workflows/license.yml
  lint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/lint.yml
  lintpubliccode:
    permissions:
      contents: read
    uses: ./.github/workflows/lint-publiccode.yml
